# -*- coding: utf-8 -*-
"""build_features_deepmodels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10JWgDTSyxC8dj_y3tavnyzhexYanCQ8T
"""

import librosa
import tensorflow as tf


def read_file_linear(path):
    y,_ = librosa.load(path)
    return y

def read_file(path):
    y, _ = librosa.load(path, sr=22050)
    return y

def spec_to_db(y):
    y_db = librosa.amplitude_to_db(y, ref=100)
    return y_db

def map_function_linear(path_tensor, label):
    y=tf.numpy_function(read_file_linear, inp= [path_tensor], Tout = tf.float32)
    spectrogram = tf.abs(tf.signal.stft(y, frame_length=512, frame_step=64))
    spectrogram_db = tf.numpy_function(spec_to_db, inp = [spectrogram], Tout = tf.float32)
    spectrogram_db = spectrogram_db/80+1
    return spectrogram_db, label

def map_function_mel(path_tensor, label):
    y = tf.numpy_function(read_file, inp=[path_tensor], Tout=tf.float32)
    spectrogram = tf.abs(tf.signal.stft(y, frame_length=512, frame_step=64))

    mel_weights = tf.signal.linear_to_mel_weight_matrix(
        num_mel_bins=128,
        num_spectrogram_bins=tf.shape(spectrogram)[-1],
        sample_rate=22050,
        lower_edge_hertz=0.0,
        upper_edge_hertz=8000.0)
    mel_spectrogram = tf.matmul(spectrogram, mel_weights)
    return mel_spectrogram, label

def map_function_mfcc(path_tensor, label):
    y = tf.numpy_function(read_file, inp=[path_tensor], Tout=tf.float32)
    spectrogram = tf.abs(tf.signal.stft(y, frame_length=512, frame_step=64))
    mel_weights = tf.signal.linear_to_mel_weight_matrix(
        num_mel_bins=128,
        num_spectrogram_bins=tf.shape(spectrogram)[-1],
        sample_rate=22050,
        lower_edge_hertz=0.0,
        upper_edge_hertz=8000.0)
    mel_spectrogram = tf.matmul(spectrogram, mel_weights)
    mfccs = tf.signal.mfccs_from_log_mel_spectrograms(tf.math.log(mel_spectrogram + 1e-6))  # Adding a small epsilon to avoid log(0)
    return mfccs, label