# -*- coding: utf-8 -*-
"""model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VppPFNncwrEnpNM7_SSF9wzG_b49Mqn-
"""

import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import joblib

def train_models(X_train, y_train):
    # Encode labels
    le = LabelEncoder()
    y_train_encoded = le.fit_transform(y_train)

    # K-Nearest Neighbors
    knn = KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_train, y_train_encoded)
    joblib.dump(knn, '/content/drive/MyDrive/archive/knn_model.pkl')

    # Random Forest
    rf = RandomForestClassifier(n_estimators=100, random_state=42)
    rf.fit(X_train, y_train_encoded)
    joblib.dump(rf, '/content/drive/MyDrive/archive/rf_model.pkl')

    # XGBoost
    xgb_clf = xgb.XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
    xgb_clf.fit(X_train, y_train_encoded)
    joblib.dump(xgb_clf, '/content/drive/MyDrive/archive/xgb_model.pkl')

    # Save the label encoder
    joblib.dump(le, '/content/drive/MyDrive/archive/label_encoder.pkl')

def main():
    # Load datasets
    X_train = np.load('/content/drive/MyDrive/archive/X_train.npy')
    y_train = np.load('/content/drive/MyDrive/archive/y_train.npy', allow_pickle=True)

    # Train models
    train_models(X_train, y_train)

if __name__ == "__main__":
    main()